baseURL = "wiki"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "ClimateTown Wiki"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/ClimateTown/wiki/edit/main/content"
  description = "A wiki of climate focused resources currated by the ClimateTown community."
  author = "ClimateTown Community"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"
  themeVariant = "green"
  custom_css = ["css/custom.css"]

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for Hugo Learn Theme"
weight = 1
languageName = "English"
landingPageURL = "/en"
landingPageName = "<i class='fas fa-home'></i> Home"


[[Languages.en.menu.shortcuts]]
name = "✍ Contribute on GitHub"
identifier = "ds"
url = "https://github.com/ClimateTown/wiki"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "📢 Credits"
url = "https://github.com/ClimateTown/wiki/graphs/contributors"
weight = 30

