name: Build website
on:
  push:
    branches: ["main", "cicd-test/*"]
  # schedule:
  #   - cron: "0 * * * *"
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v1
        id: pages
      - name: Configure Git
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "npm"
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Scrape YouTube data
        run: |
          python scripts/youtube.py --api-key ${{ secrets.YOUTUBE_API_KEY }}
      - name: Get previews for resources
        run: |
          python scripts/get_og_previews.py
      - run: npm install
      # - run: npm ci
      - run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  deploy:
    if: ${{ github.ref }} == 'refs/heads/main' and ${{ github.repository }} == 'ClimateTown/knowledge-hub'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
