name: GitHub Discord Integration
on:
  issues:
    types:
    - opened
jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Send message to Discord channel
      run: |
        python scripts/discord_integration.py \
          --webhook-url "${{ secrets.DISCORD_WEBHOOK }}" \
          --issue-number "${{ github.event.issue.number }}" \
          --issue-title "$(printf '%q' "${{ github.event.issue.title }}")" \
          --issue-description "$(printf '%q' "${{ github.event.issue.body }}")" \
          --author "$(printf '%q' "${{ github.event.issue.user.login }}")"
