name: Check URL Status

on:
  schedule:
    - cron: 0 0 * * 0

jobs:
  check_urls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.15"
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install Deps
        run: npm install
      - name: Check URL
        run: npm run broken-link-check
